### ISSUE TITLE
Naming: change "Resume" to "Continue"

### ISSUE THREAD

**Issue by sisou** [0vvland/chronos#2]
Hi! First of all, I _love_ this extension. I use it daily to track my contracting working hours.

However, I constantly find myself hesitating to click the "Resume" button, because I'm confusing it with "Restart" and will accidentaly reset the timer. I just had the epiphany that it might be the wording. Both "Resume" and "Restart" start with the same letters, and "Restart" is the stronger word for me, so I associate anything that starts with "Re" in this context as a reset/restart.

Can we try renaming "Resume" to "Continue" to make it clear that this is the non-destructive option?

**Comment by 0vvland** [comment]
Hi! Thanks for feedback. I'll try to look at it.

**Comment by 0vvland** [comment]
Changed to `Start`. It better reflect meaning of an action than `Continue` I think.
